In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [8]:
voc_size = 10000

In [9]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[5381, 9347, 3879, 6928], [5381, 9347, 3879, 8083], [5381, 4423, 3879, 8488], [8393, 4748, 3087, 2568, 117], [8393, 4748, 3087, 2568, 9398], [8648, 5381, 8260, 3879, 4451], [7822, 4912, 6456, 2568]]


In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 5381 9347 3879 6928]
 [   0    0    0    0 5381 9347 3879 8083]
 [   0    0    0    0 5381 4423 3879 8488]
 [   0    0    0 8393 4748 3087 2568  117]
 [   0    0    0 8393 4748 3087 2568 9398]
 [   0    0    0 8648 5381 8260 3879 4451]
 [   0    0    0    0 7822 4912 6456 2568]]


In [16]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [25]:
#Embedded into vectors using Embedding from keras!
print(model.predict(embedded_docs)[0][0])

[ 0.03264866  0.0051864  -0.03276018 -0.02825259  0.0063988   0.00083292
  0.04174144 -0.00301784  0.03640525  0.00949361]


In [24]:
#Word Vocabulary Indexes
embedded_docs[0]

array([   0,    0,    0,    0, 5381, 9347, 3879, 6928], dtype=int32)